language: en
pipeline: pretrained_embeddings_spacy

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: KerasPolicy
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 5
        state_featurizer:
          - name: BinarySingleStateFeaturizer
